### ISSUE TITLE
Switch to jupyter lab?

### ISSUE THREAD

**Issue by pbadenski** [n-riesco/jp-babel#22]
Jupyter lab seems to be cool kid on the block with the intention to "eventually replace the classic Jupyter Notebook."

From what I checked switching over to lab is literally as easy as replacing "notebook" with "lab" in "bin/rc.js"

Thoughts?

**Comment by n-riesco** [comment]
`jp-babel-notebook` made sense when `ipython notebook` was used to launch a kernel and open a notebook. These days, it doesn't make sense, because `jupyter notebook` opens a dashboard from which any kernel can be launched.

I was planning to keep `jp-babel-notebook` only while `jupyter notebook` works.

**Comment by pbadenski** [comment]
Oh ok, I understand now, thanks. I'm new to this, didn't realise that.
